# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiTuIJKMediaExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiTuIJKMediaExample
	pod "MiTu_IJKMediaFramework" , :path => '../'

end
